In [10]:
import torch
import numpy as np

In [36]:
from torch.nn import MaxPool2d
s = 4
n = 2
input = torch.tensor(
    np.arange(16),
    dtype = torch.float32,
)
input = input.reshape([4, -1])

input = torch.unsqueeze(input, 0)
input = torch.unsqueeze(input, 1)
input.shape

torch.Size([1, 1, 4, 4])

In [29]:
input

tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11., 12., 13., 14., 15.],
          [16., 17., 18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29., 30., 31.]]]])

In [30]:
tmp = input.clone()
output = MaxPool2d(kernel_size=2, stride=2)(tmp)
output.shape, output

(torch.Size([1, 1, 2, 4]),
 tensor([[[[ 9., 11., 13., 15.],
           [25., 27., 29., 31.]]]]))

In [31]:
from torch.nn import AvgPool2d

tmp = input.clone()
output = AvgPool2d(kernel_size=2, stride=2)(tmp)
output.shape, output

(torch.Size([1, 1, 2, 4]),
 tensor([[[[ 4.5000,  6.5000,  8.5000, 10.5000],
           [20.5000, 22.5000, 24.5000, 26.5000]]]]))

In [33]:
from torch.nn import Flatten

tmp = input.clone()
output = Flatten(start_dim=2)(tmp)
output.shape, output

(torch.Size([1, 1, 32]),
 tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
           14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
           28., 29., 30., 31.]]]))

In [42]:
from torch.nn import Dropout

tmp = torch.ones((1, 1, 4, 4))
print(f"{tmp.shape=}\n{tmp}")

dropout_layer = Dropout(p=0.75)
output = dropout_layer(tmp)
print(f"{output.shape=}\n{output}")

tmp.shape=torch.Size([1, 1, 4, 4])
tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
output.shape=torch.Size([1, 1, 4, 4])
tensor([[[[4., 0., 0., 0.],
          [0., 0., 0., 4.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


node 많으면 w 많음 => 복잡 => 에러가 나기 쉬움

In [52]:
from torch.nn import BatchNorm2d

tmp = torch.ones_like(input)
l = BatchNorm2d(num_features=1)
output = l(tmp)
output.shape, output


(torch.Size([1, 1, 4, 4]),
 tensor([[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]]], grad_fn=<NativeBatchNormBackward0>))

In [53]:
tmp

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [49]:
l.weight

Parameter containing:
tensor([1.], requires_grad=True)

In [50]:
l.bias

Parameter containing:
tensor([0.], requires_grad=True)

moving avarage를 할때 과거의 데이터의 영향을 받는데, exponential하게 되는 것은 exponential moving avarage임

이걸 BatchNormalization은 하고 있음