Tensor 인스턴스의 Storage 인스턴스

In [7]:
import torch

x = torch.randn(3,3)
x_storage = x.storage()

print(x.storage)

<bound method Tensor.storage of tensor([[ 0.2975,  1.0263, -0.3536],
        [-0.5901, -0.3142, -0.0712],
        [-1.0195,  0.8401, -0.8353]])>


In [8]:
x.untyped_storage # 최근엔 이것을 추천. byte로 되어있음 = untyped

<function Tensor.untyped_storage>

In [9]:
x_storage = x.untyped_storage()
print(x_storage)

 116
 87
 152
 62
 219
 94
 131
 63
 99
 14
 181
 190
 216
 14
 23
 191
 123
 224
 160
 190
 138
 191
 145
 189
 226
 126
 130
 191
 238
 14
 87
 63
 91
 215
 85
 191
[torch.storage.UntypedStorage(device=cpu) of size 36]


#----------------

In [53]:
import torch

a = torch.tensor([ range(i,i+3) for i in [0,3,6]])
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [54]:
a.storage()
# a.untyped_storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

여기서부터x를 a로 바꾸자

In [17]:
x.is_contiguous()#builrt_in func.임

True

In [18]:
x_sub = x[1:,0]
print(x_sub)

tensor([-0.5901, -1.0195])


In [19]:
x

tensor([[ 0.2975,  1.0263, -0.3536],
        [-0.5901, -0.3142, -0.0712],
        [-1.0195,  0.8401, -0.8353]])

In [20]:
id(x_sub) == id(x)

False

In [21]:
print(x_sub.storage())
x_sub.storage() == x.storage()

 0.2975422143936157
 1.0263322591781616
 -0.3536253869533539
 -0.5900702476501465
 -0.3142126500606537
 -0.07116611301898956
 -1.0194971561431885
 0.8400715589523315
 -0.8353173136711121
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 9]


False

In [22]:
x.untyped_storage().data_ptr() == x_sub.untyped_storage().data_ptr()

True

In [23]:
x_t = torch.transpose(x,0,1)
x_t

tensor([[ 0.2975, -0.5901, -1.0195],
        [ 1.0263, -0.3142,  0.8401],
        [-0.3536, -0.0712, -0.8353]])

In [24]:
print(x_t.storage())
x_t.is_contiguous()

 0.2975422143936157
 1.0263322591781616
 -0.3536253869533539
 -0.5900702476501465
 -0.3142126500606537
 -0.07116611301898956
 -1.0194971561431885
 0.8400715589523315
 -0.8353173136711121
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 9]


False

In [25]:
x_t[0,1] = 999
print(x_t)
print('-----')
print(x)
print('-----')
print(x_sub)

tensor([[ 2.9754e-01,  9.9900e+02, -1.0195e+00],
        [ 1.0263e+00, -3.1421e-01,  8.4007e-01],
        [-3.5363e-01, -7.1166e-02, -8.3532e-01]])
-----
tensor([[ 2.9754e-01,  1.0263e+00, -3.5363e-01],
        [ 9.9900e+02, -3.1421e-01, -7.1166e-02],
        [-1.0195e+00,  8.4007e-01, -8.3532e-01]])
-----
tensor([999.0000,  -1.0195])


In [28]:
print(f"{x.shape=}, {x.size()=}, {x.stride()=}, {x.storage_offset()=}") #conti.함
print(f"{x_t.shape=}, {x_t.size()=}, {x_t.stride()=}, {x_t.storage_offset()=}") #conti.안함 transpose되었기 때문 3,1 -> 3,1
print(f"{x_sub.shape=}, {x_sub.size()=}, {x_sub.stride()=}, {x_sub.storage_offset()=}")

x.shape=torch.Size([3, 3]), x.size()=torch.Size([3, 3]), x.stride()=(3, 1), x.storage_offset()=0
x_t.shape=torch.Size([3, 3]), x_t.size()=torch.Size([3, 3]), x_t.stride()=(1, 3), x_t.storage_offset()=0
x_sub.shape=torch.Size([2]), x_sub.size()=torch.Size([2]), x_sub.stride()=(3,), x_sub.storage_offset()=3


In [29]:
x_v = x.view((9,))
x_v

tensor([ 2.9754e-01,  1.0263e+00, -3.5363e-01,  9.9900e+02, -3.1421e-01,
        -7.1166e-02, -1.0195e+00,  8.4007e-01, -8.3532e-01])

In [30]:
x_r = x.reshape((9,))
x_r[3] = 777
print('데이터 저장공간 share')
print('x_r: af.reshape')
print(x_r)
print('x: af.original')
print(x)
print('x_t: af.transpose')
print(x_t)

데이터 저장공간 share
x_r: af.reshape
tensor([ 2.9754e-01,  1.0263e+00, -3.5363e-01,  7.7700e+02, -3.1421e-01,
        -7.1166e-02, -1.0195e+00,  8.4007e-01, -8.3532e-01])
x: af.original
tensor([[ 2.9754e-01,  1.0263e+00, -3.5363e-01],
        [ 7.7700e+02, -3.1421e-01, -7.1166e-02],
        [-1.0195e+00,  8.4007e-01, -8.3532e-01]])
x_t: af.transpose
tensor([[ 2.9754e-01,  7.7700e+02, -1.0195e+00],
        [ 1.0263e+00, -3.1421e-01,  8.4007e-01],
        [-3.5363e-01, -7.1166e-02, -8.3532e-01]])


Storage는 실제 data가 저장되는 memory를 가르키는 위치를 반환하는 메서드를 가짐.

이를 통해 실제로 Tensor 인스턴스가 Data를 공유하는지를 확인

#-------------------------------------------

Tensor 인스턴스와 이에 대한 slicing을 통한 Tensor 인스턴스의 관계를 확인

In [12]:
import torch

a = torch.tensor([range(i,i+3) for i in [0,3,6]])
a_sub = a[1:,0] # 부분에 대한 view

# Tensor a 와 a_sub 의 contiguous 여부 확인.
print(a.is_contiguous(), a_sub.is_contiguous())

# Tensor a 와 a_sub 가 같은 메모리의 데이터를 공유하는지 여부.
print(a.storage().data_ptr() == a_sub.storage().data_ptr())

# Storage 인스턴스는 각 Tensor 인스턴스 별로 생성됨.
print(id(a.storage()) == id(a_sub.storage()))

# Tensor 인스턴스의 meta data
print(f"{a.shape=}, {a.size()=}, {a.stride()=}, {a.storage_offset()=}")
print(f"{a_sub.shape=}, {a_sub.size()=}, {a_sub.stride()=}, {a_sub.storage_offset()=}")

True False
True
True
a.shape=torch.Size([3, 3]), a.size()=torch.Size([3, 3]), a.stride()=(3, 1), a.storage_offset()=0
a_sub.shape=torch.Size([2]), a_sub.size()=torch.Size([2]), a_sub.stride()=(3,), a_sub.storage_offset()=3


In [31]:
x_t.view((9,)) # not working

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [32]:
x_t_r = x_t.reshape((9,)) # uncontiguous tensor에서는 새로 생성이 이루어짐.
x_t_r

tensor([ 2.9754e-01,  7.7700e+02, -1.0195e+00,  1.0263e+00, -3.1421e-01,
         8.4007e-01, -3.5363e-01, -7.1166e-02, -8.3532e-01])

In [33]:
x_t_r[1] = 999
print(x_t_r)
print(x_t) # 달라짐.

tensor([ 2.9754e-01,  9.9900e+02, -1.0195e+00,  1.0263e+00, -3.1421e-01,
         8.4007e-01, -3.5363e-01, -7.1166e-02, -8.3532e-01])
tensor([[ 2.9754e-01,  7.7700e+02, -1.0195e+00],
        [ 1.0263e+00, -3.1421e-01,  8.4007e-01],
        [-3.5363e-01, -7.1166e-02, -8.3532e-01]])


In [34]:
act = x_t.contiguous()
act

tensor([[ 2.9754e-01,  7.7700e+02, -1.0195e+00],
        [ 1.0263e+00, -3.1421e-01,  8.4007e-01],
        [-3.5363e-01, -7.1166e-02, -8.3532e-01]])

In [35]:
act.storage()

 0.2975422143936157
 777.0
 -1.0194971561431885
 1.0263322591781616
 -0.3142126500606537
 0.8400715589523315
 -0.3536253869533539
 -0.07116611301898956
 -0.8353173136711121
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 9]

In [36]:
act[1] = 999
print(act)
print(x_t)

tensor([[ 2.9754e-01,  7.7700e+02, -1.0195e+00],
        [ 9.9900e+02,  9.9900e+02,  9.9900e+02],
        [-3.5363e-01, -7.1166e-02, -8.3532e-01]])
tensor([[ 2.9754e-01,  7.7700e+02, -1.0195e+00],
        [ 1.0263e+00, -3.1421e-01,  8.4007e-01],
        [-3.5363e-01, -7.1166e-02, -8.3532e-01]])


# permutation (순열)



* `permute`: 축의 순서를 바꿈.

In [43]:
print(a)
print('------')
print('permute axis-0 and axis-1 = transpose')
ap = a.permute([1,0]) # permute axis-0 and axis-1
ap

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
------
permute axis-0 and axis-1 = transpose


tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [46]:
a.storage().data_ptr() == ap.storage().data_ptr()

True

In [47]:
print(ap.is_contiguous())

False


In [48]:
ap2 = ap.contiguous()
a.storage().data_ptr() == ap2.storage().data_ptr()

False

In [49]:
ap2.is_contiguous()

True

In [50]:
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [51]:
ap

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [52]:
ap2

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])