# 관련 자료:

https://dsaint31.tistory.com/374


In [2]:
import numpy as np
import torch
import tensorflow as tf


In [3]:
a = [[1,2,3]]
print(type(a))
print(a)

<class 'list'>
[[1, 2, 3]]


# 1D Tensor에서의 Fancy Indexing

In [ ]:
x = np.array([10.,20.,30.,40.,50.])
x_torch = torch.tensor([10.,20.,30.,40.,50.])
x_tf = tf.constant([10.,20.,30.,40.,50.])

f_indices = [3, 4, 1]
print(x[f_indices])
print(x_torch[f_indices])
print(tf.gather(x_tf,f_indices)) #1D 에선 gahter, 2D 이상시 gather_nd
print(tf.gather_nd(x_tf, [ i for i in zip(f_indices,)])) # 굳이 쓴다면, 다음과 같이.

[40. 50. 20.]
tensor([40., 50., 20.])
tf.Tensor([40. 50. 20.], shape=(3,), dtype=float32)
tf.Tensor([40. 50. 20.], shape=(3,), dtype=float32)


# 2D Tensor에서의 Fancy Indexiing

In [ ]:
x = np.arange(5*5).reshape(5,5) * 10
x_torch = torch.arange(5*5).view(size=(5,5)) * 10
x_tf = tf.constant(x)

indices_0 = [0, 1, 2]
indices_1 = [0, 1, 2]


b = x[indices_0, indices_1]
print(b.shape)
print(b)
print('----------')
c = x_torch[indices_0, indices_1]
print(c.shape)
print(c)
print('----------')
d = tf.gather_nd(x_tf, [ i for i in zip(indices_0, indices_1)])
print(d.shape)
print(d)

(3,)
[  0  60 120]
----------
torch.Size([3])
tensor([  0,  60, 120])
----------
(3,)
tf.Tensor([  0  60 120], shape=(3,), dtype=int64)


# 3D Tensor Example

In [ ]:
x = np.arange(5*5*5).reshape(5,5,5) * 10
x_torch = torch.arange(5*5*5).view(size=(5,5,5)) * 10
x_tf = tf.constant(x)

indices_0 = [0, 1]
indices_1 = [1, 2]
indices_2 = [2, 0]

b = x[indices_0, indices_1, indices_2]
print(b.shape)
print(b)
print('----------')
c = x_torch[indices_0, indices_1, indices_2]
print(c.shape)
print(c)
print('----------')
d = tf.gather_nd(x_tf, [ i for i in zip(indices_0, indices_1, indices_2)]) # multi-dim 에선 gater_nd 임.
print(d.shape)
print(d)

(2,)
[ 70 350]
----------
torch.Size([2])
tensor([ 70, 350])
----------
(2,)
tf.Tensor([ 70 350], shape=(2,), dtype=int64)


# Boolean Mask

In [ ]:
x = np.arange(3*3*3).reshape(3,3,3) * 10

b = x <= 270/2
print(b.shape)
print(b)
print('----------')
print(x[b])
print('----------')
print(x[x<=270/2])

b1 = b | (x >= 200)
print('----------')
print(b1)
print('----------')
print(x[b1])
print('----------')
print(x[ (x<=270/2) | (x>=200)])

(3, 3, 3)
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False  True]
  [ True  True  True]
  [ True  True  True]]]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 240 250 260]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 240 250 260]


In [ ]:
x_torch = torch.arange(3*3*3).view(size=(3,3,3)) * 10

print(x_torch[ (x_torch<=270/2) | (x_torch>=200)])



tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        200, 210, 220, 230, 240, 250, 260])


In [ ]:
x_tf = tf.constant(x)

print(x_tf[ (x_tf<= tf.cast(270/2, tf.int64)) | (x_tf>=200)])

tf.Tensor(
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 240 250 260], shape=(21,), dtype=int64)


# combined indexing

기존의 scalar indexing, slicing, fancy indexing, boolear mask 등을 서로 조합하여 사용하는 것.

numpy에선 효용도가 있으나,
pytorch 나 tensorflow 에서는 사용이 쉽지 않음 (고차원에선 처리가 쉽지 않ㅁ)

In [ ]:
import numpy as np

x = np.array([0,1,2,3,4,5,6,7,8]).reshape((3,3))
print(x.shape)

mask = np.array([True, False, True])
cidx = np.array([2,0,1])
print(mask.shape)
print(cidx.shape)

print('--------')
print(x)
print('--------')
print(x[mask,cidx[:,np.newaxis]]) # broadcasting 으로 fancyindexing 이 이루어짐.

(3, 3)
(3,)
(3,)
--------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------
[[2 8]
 [0 6]
 [1 7]]


In [ ]:
import torch

x_torch = torch.tensor([0,1,2,3,4,5,6,7,8]).reshape((3,3))
if torch.cuda.is_available():
    x_torch = x_torch.to("cuda")

x_torch[mask,cidx[:,np.newaxis]]

tensor([[2, 8],
        [0, 6],
        [1, 7]], device='cuda:0')

In [ ]:
a = np.array([1,0,1])
b = cidx[:,np.newaxis]
a*b

array([[2, 0, 2],
       [0, 0, 0],
       [1, 0, 1]])

In [ ]:
x = np.array([0,1,2,3,4,5,6,7,8]).reshape((3,3))

# booelan mask 대신, 일반적인 수치로도 가능.
r = x[[0,2],cidx[:,np.newaxis]] # combined indexing의 경우, ₩내부에서 broadcasting 룰이 적용됨.

print(x)
print('--------')
print(r)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------
[[2 8]
 [0 6]
 [1 7]]


In [ ]:
import numpy as np

x = np.array([0,1,2,3,4,5,6,7]).reshape(2,2,2)
t = np.array([0,1])
r = x[[False,True],t[np.newaxis,:]]
print(x.shape)
print(x)
print('--------')
print(r.shape)
print(r)
print('--------')
print(t[np.newaxis, :].shape)
print(t[np.newaxis, :])

(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
--------
(1, 2, 2)
[[[4 5]
  [6 7]]]
--------
(1, 2)
[[0 1]]


# fancy indexing을 활용한 처리.

In [ ]:
x = np.arange(10).reshape(1,10)
print('before:',x)
r_idx = np.array([0])
c_idx = np.array([9, 1, 3, 9]) # 중복되어도 더해지진 않음.
x[r_idx,c_idx] = x[r_idx,c_idx] +10
print('after :',x)

before: [[0 1 2 3 4 5 6 7 8 9]]
after : [[ 0 11  2 13  4  5  6  7  8 19]]


In [ ]:
x = np.arange(10)
print('before:',x)
np.add.at(x,i,10) # 중복된 index를 더해줌.
print('after :',x)

before: [0 1 2 3 4 5 6 7 8 9]
after : [ 0 11  2 13  4  5  6  7  8 29]


In [ ]:
x_torch = torch.arange(10)
print(x_torch.dtype)
print('before:',x_torch)
i = torch.tensor([9, 1, 3, 9]) # 중복되어도 더해지진 않음.
x_torch[i] = x_torch[i] +10
print('after :',x_torch)

torch.int64
before: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
after : tensor([ 0, 11,  2, 13,  4,  5,  6,  7,  8, 19])


In [ ]:
import numpy as np

rng = np.random.default_rng(1)
x = rng.random((5,2))


In [ ]:
y0 = x[:, np.newaxis]
.shape

(5, 1, 2)

# Fancy Indexing

In [ ]:
import numpy as np
x = np.array([0,1,2,3,4,5,6,7,8])

In [ ]:
fidx = [3,7,1]
x[fidx]

array([3, 7, 1])

In [ ]:
fidx = [[3,7],
        [4,2]]
fidx = np.array(fidx)
x[fidx]

array([[3, 7],
       [4, 2]])

In [ ]:
x = x.reshape(3,3)
ridx = np.array([0,1,2])
cidx = np.array([2,0,1])
x[ridx,cidx]

array([2, 3, 7])

In [ ]:
fidx = np.array(
    [ [[0,0],[0,1]],
     [[1,0],[1,1]]]
)
a = x[fidx]
a.shape

(2, 2, 2, 3)

In [ ]:
fidx.shape

(2, 2, 2)

In [ ]:
fidx[0,1]

array([0, 1])

In [ ]:
a[0,1]

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
cidx[:,np.newaxis]

array([[2],
       [0],
       [1]])

In [ ]:
cidx.shape

(3,)

In [ ]:
[0,2], cidx[:,np.newaxis]

([0, 2],
 array([[2],
        [0],
        [1]]))

In [ ]:
x[[0,2],cidx[:,np.newaxis]]

array([[2, 8],
       [0, 6],
       [1, 7]])

In [ ]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# PyTorch에서 list를 indexing tensor로 삼을 경우 비교.


In [ ]:
import torch
import numpy as np

a_np = np.arange(2*3*4).reshape(2,3,4)
a = torch.arange(2*3*4).reshape(2,3,4)
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## non-nested list의 경우

tensor, ndarray, list 모두 같은 결과를 보임.

In [ ]:
i_list0 = [0,0] # unpakcing시 scalar이므로 a[i_list0,] 와 같이 동작
a[i_list0].shape

torch.Size([2, 3, 4])

In [ ]:
a_np[i_list0].shape # ndarray도 같은 동작임.

(2, 3, 4)

In [ ]:
a[i_list0,].shape # i_list1의 item scalar인 경우만 같음.

torch.Size([2, 3, 4])

In [ ]:
a_np[i_list0,].shape # ndarray도 같은 동작임.

(2, 3, 4)

In [ ]:
a[torch.tensor(i_list0)].shape # 항상 a[i_list0,]과 같음.

torch.Size([2, 3, 4])

In [ ]:
a_np[np.array(i_list0)].shape # 역시 같은 동작

(2, 3, 4)

## nested list: 1x2 의 경우



In [ ]:
i_list1 = [ [0,0] ] # axis-0를 제거해도 scalar가 아닌 list임.
a[i_list1].shape

torch.Size([2, 3, 4])

In [ ]:
a_np[i_list1].shape # NumPy에서는 list나 array나 indexing에 사용에서 같은 동작을 보임.

(1, 2, 3, 4)

In [ ]:
a[i_list1,].shape # unpacking시 scalar인 경우에만 같으므로 다른 결과

torch.Size([1, 2, 3, 4])

In [ ]:
a_np[i_list1,].shape # NumPy에선 i_list1과 차이 없음.

(1, 2, 3, 4)

In [ ]:
a[torch.tensor(i_list1)].shape # a[i_list1,] 와 항상 같은 결과

torch.Size([1, 2, 3, 4])

## 1x1x2 의 경우

원칙에 변함이 없음.

* NumPy에선 index tensor로 list나 array 둘 다 같은 결과.
* PyTorch에선 nested list이므로 list는 axis-0의 요소들이 분해되어 동작.

In [ ]:
i_list2 = [ [ [0,0] ]] # 참고삼아 1차원을 더 넓힌 경우, 1x1x2 이므로 1x2가 첫번째 index로 주어짐.
a[i_list2].shape # 1x2 형태로 a[0],a[1] 가 놓임

torch.Size([1, 2, 3, 4])

In [ ]:
a[*i_list2].shape # unpacking!

torch.Size([1, 2, 3, 4])

In [ ]:
a_np[i_list2].shape

(1, 1, 2, 3, 4)

In [ ]:
a_np[np.array(i_list2)].shape

(1, 1, 2, 3, 4)

In [ ]:
a[i_list2,].shape

torch.Size([1, 1, 2, 3, 4])

In [ ]:
a[torch.tensor(i_list2)].shape

torch.Size([1, 1, 2, 3, 4])

## 2x2 인 경우.

원칙은 그대로임.

In [ ]:
i_list3 = [ [0,1] , [1,0]] # axis-0 의 각 요소가 scalar 아님.
                           # a[i_list3[0],i_list3[1]] 과 같음.
a[i_list3].shape

torch.Size([2, 4])

In [ ]:
a[*i_list3].shape

torch.Size([2, 4])

In [ ]:
a[i_list3[0], i_list3[1]].shape # 분해되어 들어가는 것과 같음.

torch.Size([2, 4])

In [ ]:
a[i_list3,].shape # 뒤의 ,로 인해 tuple로 인식되고 이로 인해 axis-0가 풀리지 않음.

torch.Size([2, 2, 3, 4])

In [ ]:
a[torch.tensor(i_list3)].shape # a[i_list3,] 과 같은 결과임.

torch.Size([2, 2, 3, 4])

In [ ]:
a_np[i_list3].shape # NumPy에선 tensor와 같은 결과.

(2, 2, 3, 4)

In [ ]:
a_np[np.array(i_list3)].shape #ndarray 역시 마찬가지임.

(2, 2, 3, 4)

## 3x2 의 경우

In [ ]:
i_list4 = [ [0,0], [0,1], [1,1] ] # 3개로 분해되어 들어감.
                                  # a[i_list4[0],i_list4[1],i_list4[2]]
a[i_list4].shape

torch.Size([2])

In [ ]:
a[i_list4[0],i_list4[1],i_list4[2]].shape # 동일함을 확인 할 수 있음.
                                          # [a[0,0,1], a[0,1,1]] 을 반환

torch.Size([2])

In [ ]:
a[*i_list4].shape

torch.Size([2])

In [ ]:
a[i_list4,].shape # 이는 tensor로 바꾼 것과 같은 결과.
                  # 3x2 개의 a[i]가 존재하니 3x2x3x4 가 됨.

torch.Size([3, 2, 3, 4])

In [ ]:
a[torch.tensor(i_list4)].shape

torch.Size([3, 2, 3, 4])

In [ ]:
a_np[i_list4].shape

(3, 2, 3, 4)

In [ ]:
a_np[np.array(i_list4)].shape

(3, 2, 3, 4)

## 4x4 의 경우

이 경우 dimension-0 (or axis-0)가 4로 원본 텐서의 ndim(=3)보다 큼.

In [ ]:
# scalar를 item으로 가지지 않는 list는 unpacking이 되어 들어가므로
# scalar를 itme으로 가지지 않으면서 원본 tensor의 ndim보다 많은
# axis-0 의 size를 가질 경우 동작하지 않음.
i_list5= [
    [0,1,0,1],
    [0,0,0,0],
    [1,1,0,0],
    [1,1,1,1],
]
a[i_list5]

IndexError: too many indices for tensor of dimension 3

In [ ]:
# 하지만 ,를 붙여서 tensor로 넘긴 효과를 주면 동작함.
a[i_list5,].shape

torch.Size([4, 4, 3, 4])

In [ ]:
a[torch.tensor(i_list5)].shape

torch.Size([4, 4, 3, 4])

In [ ]:
a_np[i_list5].shape

(4, 4, 3, 4)

In [ ]:
a_np[np.array(i_list5)].shape

(4, 4, 3, 4)