# PyTorch에서 list를 indexing tensor로 삼을 경우 비교.

In [ ]:
import torch
import numpy as np

a_np = np.arange(2*3*4).reshape(2,3,4)
a = torch.arange(2*3*4).reshape(2,3,4)
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## non-nested list의 경우

tensor, ndarray, list 모두 같은 결과를 보임.

In [ ]:
i_list0 = [0,0] # unpakcing시 scalar이므로 a[i_list0,] 와 같이 동작
a[i_list0].shape

torch.Size([2, 3, 4])

In [ ]:
a[i_list0] # a[0]가 0번째 축에 2개 반복되어 놓임.

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [ ]:
a_np[i_list0].shape # ndarray도 같은 동작임.

(2, 3, 4)

In [ ]:
a[i_list0,].shape # i_list1의 item scalar인 경우만 같음.

torch.Size([2, 3, 4])

In [ ]:
a_np[i_list0,].shape # ndarray도 같은 동작임.

(2, 3, 4)

In [ ]:
a[torch.tensor(i_list0)].shape # 항상 a[i_list0,]과 같음.

torch.Size([2, 3, 4])

In [ ]:
a_np[np.array(i_list0)].shape # 역시 같은 동작

(2, 3, 4)

## nested list: 1x2 의 경우

원칙은 다음과 같음.

* NumPy에선 index tensor로 list나 array 둘 다 같은 결과.
* PyTorch에선 nested list이므로 list는 axis-0의 요소들이 분해(unpacking)되어 동작.
* 단, list를 index로 넘겨줄 때, 뒤에 ,를 붙이면 unpacking이 일어나지 않고 index tensor처럼 동작.


In [ ]:
i_list1 = [ [0,0] ] # axis-0를 제거해도 scalar가 아닌 list임.
a[i_list1].shape    # unpacking 되어 들어감. a[ [0,0], ] 의 형태
                    # 1x2 가 unpacking되어 2 가 되고, 이 것이 axis-0를 결정
                    # 즉, 2 x 3x4 가 결과 tensor임.

torch.Size([2, 3, 4])

In [ ]:
a[i_list1]  # a[0]가 0번째 축에 2개 반복되어 놓임.

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [ ]:
tmp = a[*i_list1] # nested list와 같이 동작함 (non-nested list인 경우만 제외하곤)
tmp.shape, tmp

(torch.Size([2, 3, 4]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]]]))

In [ ]:
a_np[i_list1].shape # NumPy에서는 list나 array나 indexing에 사용에서 같은 동작을 보임.
                    # unpacking 없이 [[0,0]]으로 들어감 = a[ [[0,0]] ]
                    # i_list1 이 1x2 형태 이므로 axis-0에가 1x2로 교체되어
                    # 최종으로는 1x2 x 3x4로 바뀜.

(1, 2, 3, 4)

In [ ]:
a[i_list1,].shape # 뒤에 , 를 넣어줄 경우, 명시적으로 axis-0에 지정한다는 뜻임.
                  # unpacking이 이루어지지 않으며, 이 경우엔
                  # non-nested list 처럼 index tensor와 같은 결과를 보임.

torch.Size([1, 2, 3, 4])

In [ ]:
a_np[i_list1,].shape # NumPy에선 i_list1과 차이 없음.

(1, 2, 3, 4)

In [ ]:
a[torch.tensor(i_list1)].shape # index tensor를 사용한 경우
                               # a[i_list1,] 와 항상 같은 결과

torch.Size([1, 2, 3, 4])

## 1x1x2 의 경우

원칙에 변함이 없음.

* NumPy에선 index tensor로 list나 array 둘 다 같은 결과.
* PyTorch에선 nested list이므로 list는 axis-0의 요소들이 분해되어 동작.

In [ ]:
i_list2 = [ [ [0,0] ]] # 참고삼아 1차원을 더 넓힌 경우임.
                       # 1x1x2 이므로 바깥쪽만 unpacking되어
                       # 1x2가 첫번째 index로 주어짐.
a[i_list2].shape       # axis-0에 1x2 형태로 a[0],a[1] 가 놓임

torch.Size([1, 2, 3, 4])

In [ ]:
a[*i_list2].shape # unpacking!

torch.Size([1, 2, 3, 4])

In [ ]:
a_np[i_list2].shape # NumPy에선 unpacking없이 np.array를 index로 삼은것과 같이 동작

(1, 1, 2, 3, 4)

In [ ]:
a_np[np.array(i_list2)].shape # 역시 동일

(1, 1, 2, 3, 4)

In [ ]:
a[i_list2,].shape # 뒤의 comma 때문에 index tensor와 같이 동작함

torch.Size([1, 1, 2, 3, 4])

In [ ]:
a[torch.tensor(i_list2)].shape

torch.Size([1, 1, 2, 3, 4])

## 2x2 인 경우.

원칙은 그대로임.

In [ ]:
i_list3 = [ [0,1] , [1,0]] # axis-0 의 각 요소가 scalar 아님.
                           # a[i_list3[0],i_list3[1]] 과 같음.
a[i_list3].shape

torch.Size([2, 4])

In [ ]:
a[*i_list3].shape # 즉 위의 경우는 이처럼 unpacking을 한 것임.

torch.Size([2, 4])

In [ ]:
a[i_list3[0], i_list3[1]].shape # 분해되어 들어가는 것과 같음.

torch.Size([2, 4])

In [ ]:
a[i_list3,].shape # 뒤의 ,로 인해 index로 주어진 list의 axis-0가 풀리지 않음.

torch.Size([2, 2, 3, 4])

In [ ]:
a[torch.tensor(i_list3)].shape # a[i_list3,] 과 같은 결과임.

torch.Size([2, 2, 3, 4])

In [ ]:
a_np[i_list3].shape # NumPy에선 tensor와 같은 결과.

(2, 2, 3, 4)

In [ ]:
a_np[np.array(i_list3)].shape #ndarray 역시 마찬가지임.

(2, 2, 3, 4)

## 3x2 의 경우

In [ ]:
i_list4 = [ [0,0], [0,1], [1,1] ] # 3개로 분해되어 들어감.
                                  # a[i_list4[0],i_list4[1],i_list4[2]]
a[i_list4].shape

torch.Size([2])

In [ ]:
a.shape, a

(torch.Size([2, 3, 4]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]))

In [ ]:
a[i_list4] # a[0,0,1] (=1) 과 a[0,1,1] (=5) 로 구성된 2개의 요소가지는 tensor

tensor([1, 5])

In [ ]:
a[i_list4[0],i_list4[1],i_list4[2]].shape # 동일함을 확인 할 수 있음.
                                          # [a[0,0,1], a[0,1,1]] 을 반환

torch.Size([2])

In [ ]:
a[i_list4[0],i_list4[1],i_list4[2]]

tensor([1, 5])

In [ ]:
a[*i_list4].shape # unpacking으로 표현

torch.Size([2])

In [ ]:
print(*i_list4) # unpacking 확인하는 방법

[0, 0] [0, 1] [1, 1]


In [ ]:
a[i_list4,].shape # 이는 tensor로 바꾼 것과 같은 결과.
                  # 3x2 개의 a[i]가 존재하니 3x2x3x4 가 됨.

torch.Size([3, 2, 3, 4])

In [ ]:
a[torch.tensor(i_list4)].shape

torch.Size([3, 2, 3, 4])

In [ ]:
a_np[i_list4].shape

(3, 2, 3, 4)

In [ ]:
a_np[np.array(i_list4)].shape

(3, 2, 3, 4)

## 4x4 의 경우

이 경우 dimension-0 (or axis-0)가 4로 원본 텐서의 ndim(=3)보다 큼.

In [ ]:
# scalar를 item으로 가지지 않는 list는 unpacking이 되어 들어가므로
# scalar를 itme으로 가지지 않으면서 원본 tensor의 ndim보다 많은
# axis-0 의 size를 가질 경우 동작하지 않음.
i_list5= [
    [0,1,0,1],
    [0,0,0,0],
    [1,1,0,0],
    [1,1,1,1],
]
a[i_list5]

IndexError: too many indices for tensor of dimension 3

In [ ]:
# 하지만 ,를 붙여서 tensor로 넘긴 효과를 주면 동작함.
# axis-0 가 4x4로 대체되어
# 4x4 x 3x4 가 결과임.
a[i_list5,].shape

torch.Size([4, 4, 3, 4])

In [ ]:
a[torch.tensor(i_list5)].shape

torch.Size([4, 4, 3, 4])

In [ ]:
a_np[i_list5].shape

(4, 4, 3, 4)

In [ ]:
a_np[np.array(i_list5)].shape

(4, 4, 3, 4)