In [ ]:
import numpy as np
import tensorflow as tf
import torch

In [ ]:
a = np.ones((3,3))
b = np.uint8(a)
c = a.astype('float32')
print(f"{c = }")

print(f"{a.dtype = }\n{b.dtype = }\n{c.dtype = }")
print(f"{np.may_share_memory(a,b) = }")
print(f"{np.may_share_memory(a,c) = }")
print(f"{np.may_share_memory(b,c) = }")

c = array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)
a.dtype = dtype('float64')
b.dtype = dtype('uint8')
c.dtype = dtype('float32')
np.may_share_memory(a,b) = False
np.may_share_memory(a,c) = False
np.may_share_memory(b,c) = False


In [ ]:
c[0,0] = 1000
print(f"{a = }")
print("---------")
print(f"{c = }")

a = array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
---------
c = array([[1000.,    1.,    1.],
       [   1.,    1.,    1.],
       [   1.,    1.,    1.]], dtype=float32)


### PyTorch

In [ ]:
def share_memory(a,b):
  return a.untyped_storage().data_ptr() == b.untyped_storage().data_ptr()

In [ ]:
a_torch = torch.rand(3,4)
b_torch = a_torch.to(torch.uint8)
c_torch = a_torch.type(torch.float64)
print(f"{a_torch.dtype = }\n{b_torch.dtype = }\n{c_torch.dtype = }")
print("-----------")
print(f"{share_memory(a_torch,b_torch) = }")
print(f"{share_memory(a_torch,c_torch) = }")
print(f"{share_memory(b_torch,c_torch) = }")
print("-----------")
b_torch[0,1] = 9
c_torch[0,0] = 1000
print(f"{a_torch = }")
print(f"{b_torch = }")
print(f"{c_torch = }")

a_torch.dtype = torch.float32
b_torch.dtype = torch.uint8
c_torch.dtype = torch.float64
-----------
share_memory(a_torch,b_torch) = False
share_memory(a_torch,c_torch) = False
share_memory(b_torch,c_torch) = False
-----------
a_torch = tensor([[0.3738, 0.5342, 0.0702, 0.0080],
        [0.1860, 0.7505, 0.4290, 0.7671],
        [0.3760, 0.1961, 0.2042, 0.5005]])
b_torch = tensor([[0, 9, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
c_torch = tensor([[1.0000e+03, 5.3418e-01, 7.0162e-02, 8.0060e-03],
        [1.8603e-01, 7.5053e-01, 4.2901e-01, 7.6709e-01],
        [3.7597e-01, 1.9611e-01, 2.0425e-01, 5.0046e-01]], dtype=torch.float64)


In [ ]:
print(f"{a_torch = }")
c_torch[0,0] = 777.
print(f"{a_torch = }")
print(f"{c_torch = }")

a_torch = tensor([[0.3738, 0.5342, 0.0702, 0.0080],
        [0.1860, 0.7505, 0.4290, 0.7671],
        [0.3760, 0.1961, 0.2042, 0.5005]])
a_torch = tensor([[0.3738, 0.5342, 0.0702, 0.0080],
        [0.1860, 0.7505, 0.4290, 0.7671],
        [0.3760, 0.1961, 0.2042, 0.5005]])
c_torch = tensor([[7.7700e+02, 5.3418e-01, 7.0162e-02, 8.0060e-03],
        [1.8603e-01, 7.5053e-01, 4.2901e-01, 7.6709e-01],
        [3.7597e-01, 1.9611e-01, 2.0425e-01, 5.0046e-01]], dtype=torch.float64)


In [ ]:
d_torch = a_torch.to(torch.float64)
print(f"{share_memory(a_torch,d_torch) = }")

share_memory(a_torch,d_torch) = False


In [ ]:
e_torch = a_torch.float()
print(f"{a_torch.dtype = }")
print(f"{e_torch.dtype = }")
print(f"{share_memory(a_torch,e_torch) = }")

a_torch.dtype = torch.float32
e_torch.dtype = torch.float32
share_memory(a_torch,e_torch) = True


In [ ]:
f_torch = a_torch.int()
print(f"{a_torch.dtype = }")
print(f"{f_torch.dtype = }")
print(f"{share_memory(a_torch,f_torch) = }")

a_torch.dtype = torch.float32
f_torch.dtype = torch.int32
share_memory(a_torch,f_torch) = False


### TensorFlwo

In [ ]:
import tensorflow as tf

a_tf = tf.random.uniform(shape=(3,4))
c_tf = tf.dtypes.cast(a_tf, tf.float64)
print(f"{a_tf.dtype = }\n{c_tf.dtype = }")

# # not working
# print(f"{tf.experimental.numpy.shares_memory(a_tf,c_tf) = }")

a_tf.dtype = tf.float32
c_tf.dtype = tf.float64


# shape 변경

### NumPy

In [ ]:
a = np.arange(0,10,1) # [ s:e :step_size]
b = a.reshape((2,5))
print(f"{a.shape = }\n{b.shape = }")
print(f"{np.may_share_memory(a,b) = }")

a.shape = (10,)
b.shape = (2, 5)
np.may_share_memory(a,b) = True


In [ ]:
c = np.reshape(a,(5,2))
print(f"{c.shape = }")
print(f"{np.may_share_memory(a,c) = }")

c.shape = (5, 2)
np.may_share_memory(a,c) = True


In [ ]:
c[0,0] = 1000
print(f"{a = }")
print(f"{b = }")
print(f"{c = }")

a = array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])
b = array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])
c = array([[1000,    1],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8,    9]])


### PyTorch

In [ ]:
a_torch = torch.arange(0,10,1)
b_torch = a_torch.reshape((2,5))
print(f"{a_torch.shape = }\n{b_torch.shape} = ")
print(f"{share_memory(a_torch,b_torch) = }")

a_torch.shape = torch.Size([10])
torch.Size([2, 5]) = 
share_memory(a_torch,b_torch) = True


In [ ]:
c_torch = torch.reshape(a_torch,(5,2))
print(f"{c_torch.shape = }")
print(f"{share_memory(a_torch,c_torch) = }")

c_torch.shape = torch.Size([5, 2])
share_memory(a_torch,c_torch) = True


In [ ]:
c_torch[0,0] = 1000

print(f"{a_torch = }")
print(f"{b_torch = }")
print(f"{c_torch = }")

a_torch = tensor([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])
b_torch = tensor([[1000,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
c_torch = tensor([[1000,    1],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])


### TensorFlow

* TensorFlow는 메모리 최적화와 효율성을 위해 내부적으로 복잡한 메모리 관리를 수행
* PyTorch나 NumPy처럼 명확하게 메모리 공유 상태를 확인하는 공식 API는 제한적

> 기본적으로 새로 만들어진다고 보면 됨.

In [ ]:
a_tf = tf.range(0,10,1)
b_tf = tf.reshape(a_tf,(2,5))
# b_tf = a_tf.reshape((2,5)) # not working
print(f"{a_tf.shape = }\n{b_tf.shape = }")
# not working!
# print(f"{tf.experimental.numpy.shares_memory(a_tf,b_tf) = }")

a_tf.shape = TensorShape([10])
b_tf.shape = TensorShape([2, 5])


In [ ]:
c_tf = tf.reshape(a_tf,(5,2))
print(f"{c_tf.shape = }")

c_tf.shape = TensorShape([5, 2])


In [ ]:
# 변경하고 싶은 위치와 값을 정의
indices = tf.constant([[0, 0]]) # (2, 2) 위치를 변경하고자 함
updates = tf.constant([999]) # 해당 위치에 넣고 싶은 값

# 업데이트 적용
d_tf = tf.tensor_scatter_nd_update(c_tf, indices, updates)

print(f"{a_tf = }")
print(f"{b_tf = }")
print(f"{c_tf = }")
print(f"{d_tf = }")

a_tf = <tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>
b_tf = <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int32)>
c_tf = <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=int32)>
d_tf = <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[999,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]], dtype=int32)>
