In [ ]:
import numpy as np
import tensorflow as tf
import torch

In [ ]:
t = (1,2,3,4,5,6)

a = np.array(t)
a_tf = tf.constant(t)
a_torch = torch.tensor(t)

In [ ]:
a1 = a_tf.numpy()
a2 = a_torch.numpy()

In [ ]:
a2[0] = 777
print(a2)
print(a_torch)

[777   2   3   4   5   6]
tensor([777,   2,   3,   4,   5,   6])


In [ ]:
print(a1)
print(a_tf)
a1[0] = 888
print(a1)
print(a_tf)

[1 2 3 4 5 6]
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
[888   2   3   4   5   6]
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
print(a_torch)
a3 = a_torch.numpy().copy()
a3[0] = 999
print(a3)
print(a_torch)

tensor([777,   2,   3,   4,   5,   6])
[999   2   3   4   5   6]
tensor([777,   2,   3,   4,   5,   6])


In [ ]:
type(a_torch.data)

torch.Tensor

In [ ]:
a_tf = tf.convert_to_tensor(a)
a_torch = torch.from_numpy(a)
print(a_tf)
print(a_torch)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int64)
tensor([1, 2, 3, 4, 5, 6])


In [ ]:
a_torch[0] = 999
print(a_torch)
print(a)

tensor([999,   2,   3,   4,   5,   6])
[999   2   3   4   5   6]
