In [2]:
import numpy as np
import torch

In [3]:
np.__version__

'1.26.4'

In [4]:
torch.__version__

'2.5.1+cu124'

# Randomness 고정하기.

In [5]:
np.random.seed(23) #seed가 시작점이고, 이 seed 뒤부턴 거의 동일함. s여기선 edd는 23으로 고정됨

In [6]:
torch.manual_seed(23)
torch.backends.cudnn.deterministic = True # 연산속도가 느려짐. 학습단계에선 권하지 않음. 여기서 고정된 것
torch.backends.cudnn.benchmark = False #하지만 이 줄 처럼 끄면 엄청 느려짐

In [10]:
# python randomness 제어.
import random

random.seed(23)

---

---

# Uniform Distribution

## np.random.randint, torch.randint

주어진 범위 내에서 정수의 난수 생성 (uniform distribution)하는데 이용됨.

* `np.random.choice` 와 매우 유사하지만,  
* 뽑히는 값을 가지고 있는 array를 첫번째 argument로 받는 `np.random.choice` 와 달리,  
* positional argument로 `min`, `max+1` 의 형태로 분리하여 값의 범위를 지정함.  
* 하나의 int로 값의 범위를 지정할 경우, `max+1` 로 처리됨.

> `torch.randint` 에서 제공.

다음 예를 확인할 것.

In [12]:
np.random.randint(3, size=(3,2)) # 3은 0부터 3까지, 3,2는 세로3, 가로2

array([[1, 0],
       [0, 1],
       [0, 1]])

In [20]:
# min, max+1, size
np.random.randint(3,5, size=5)

array([3, 3, 4, 3, 3])

In [24]:
# min, max+1, size
torch.randint(3,5, size=(5,)) # size에 tuple로 입력받아야 함. scalar로 입력시 error.
# but. rand는 위에처럼 size를 tuple로 감싸주는게 좀 까다로움

tensor([4, 3, 4, 4, 3])

In [25]:
 torch.randint(5, size=(5,))

tensor([2, 0, 2, 4, 3])

## np.random.choice

uniform distribution으로 array로 주어진 값들로 이루어진 array를 반환.

* 첫번째 argument로 1d ndarray 객체의 요소들을 입력받아, 해당 array의 item들을 같은 확률로 뽑하내어   
* 두번째 argument로 주어진 `size`에 해당하는 shape의
* array 인스턴스를 반환.

> `torch`에서 그대로 지원하지는 않으나,  
> 가장 유사한 기능을 `torch.randperm(max+1)` 가 지원됨.

다음의 예제는

3,4,5 의 값들을 각각 1/3 의 확률로 선택하여,
$2 \times 3$ array 인스턴스를 반환함.

In [26]:
vals = np.array([3,4,5])

np.random.choice(vals, size=(2,3))

array([[5, 5, 5],
       [4, 5, 4]])

다음은 3 이라는 scalar 값을 argument로 줄 경우,

0부터 3-1=2의 값을 동일확률로 선택하여  
`size=(2,3)`에 걸맞는 $2\times 3$ array 인스턴스를 반환함.

In [30]:
np.random.choice(3, size=(2,3)) #

array([[0, 2, 1],
       [1, 1, 0]])

In [31]:
vals = np.array([0., 0.5, 1.]) # int만 사용하지는건 아님
np.random.choice(vals, size=(2,2))

array([[0.5, 1. ],
       [0. , 0.5]])

`torch.randperm` 은 하나의 argument로 `int` 형의 숫자를 입력받아 0부터 해당 숫자-1까지의 `int`를 무작위로 섞어서 만든 tensor 객체를 반환함.

In [32]:
torch.randperm(3)

tensor([0, 2, 1])

## np.random.rand and torch.rand

uniform distribution에 기반.

[0,1) 의 범위 내의 값들로 구성된 array를 만들지만, 각 차원의 크기를 분리된 argument로 받는다는 특징을 가짐.

* `np.random.random_sample`과 `np.random.random` 과 비슷.
* 단, 각 차원의 크기를 각각 argument 로 받음.
* (`random_sample` 은 tuple 등으로 하나의 argument로 받음)

> `torch.rand` 로 지원됨.

In [36]:
np.random.rand(2,3)

array([[0.04375338, 0.69617197, 0.24759255],
       [0.98908649, 0.78330846, 0.49698947]])

In [37]:
# Error
# np.random.random_sample 또는 np.random.random 과 달리
# shape를 하나의 collection type로 입력받을 경우
# 동작하지 않음.
np.random.rand((2,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [38]:
torch.rand((2,3)) # [0,1) 내에서의 숫자로 tensor 생성.

tensor([[0.3122, 0.1976, 0.5466],
        [0.0213, 0.9049, 0.8444]])

In [41]:
np.random.random((2,3))

torch.rand(2,3)

tensor([[0.9330, 0.2950, 0.4773],
        [0.4787, 0.3440, 0.6732]])

## np.random.random_sample

uniform distribution 에 기반.

* `size`로 주어진 shape로,
* 다음의 범위 [0.0, 1.0) 내의 값을 동일한 확률로 뽑아내어
* array객체를 반환.

size를 나타내는 argument가 1개로 주어져야 하므로 collection type의 객체로 주어짐.

> `np.random.random` 과 같은 기능임.

`torch`에서는 지원하지 않음.

In [42]:
np.random.random_sample((2,3))

array([[0.85117401, 0.75826885, 0.33062283],
       [0.54606087, 0.66616536, 0.97966744]])

In [44]:
# Error: 분리하여 shape를 지정할 수 없음.
np.random.random_sample(2,3)

TypeError: random_sample() takes at most 1 positional argument (2 given)

## np.random.random

`np.random.random_sample` 과 같은 기능.

> `torch` 에서 지원하지 않음.

---

---

# Normal Distribution

## np.random.normal and torch.normal

normal distribution 에 기반하기 때문에 다음의 3개의 argument와 같이 호출됨.

* `mean`: mean
* `std`: standard deviation
* `size`: 결과 array의 shape에 해당.

`mean`과 `std`가 생략될 경우, 0과 1이 기본값으로 설정됨.  
(이 경우는 `np.random.standard_norma` 과 같음)

> `torch.normal`로 지원됨.

In [45]:
np.random.normal(1,2, size=(2,3))

array([[ 5.93381036, -1.13553168,  0.20318666],
       [-0.25757176,  0.07809645,  2.24464844]])

In [46]:
np.random.normal(size=(2,3))

array([[-1.45536865,  0.00526793,  0.92413789],
       [-1.04952012, -1.31319176,  0.43805064]])

In [47]:
torch.normal(1,2,size=(2,3))

tensor([[ 0.5636,  3.8123,  0.2391],
        [-0.9122, -0.3682,  1.7205]])

## np.random.randn and torch.randn

standard normal distribution에 기반.

단, shape를 분리된 arguments로 반환되는 array 객체의 shape가 결정됨.

> `torch.randn` 으로 지원.

In [48]:
np.random.randn(2,3)

array([[-0.26227358,  0.33485026, -0.00409705],
       [-0.48021776, -0.61902472, -0.13071634]])

In [49]:
torch.randn(2,3)

tensor([[ 1.1056,  0.6353,  0.2864],
        [-1.0203, -0.6752, -0.5612]])

## np.random.standard_normal

standard normal distribution에 기반.

즉, `mean=0.` 이고 `std=1` 이며,  
`size`를 이용하여 반환되는 array 객체의 shape가 결정됨.

> `torch` 에서 제공하지 않음.

In [50]:
np.random.standard_normal(size=(2,3))

array([[-0.13056894, -0.43515686, -0.25809151],
       [-1.07148856, -0.87069574,  0.50169634]])

---

---

# PyTorch: Same shape as input tensor

PyTorch 의 경우, 특정 tensor 인스턴스와 같은 shape로 random tensor를 생성하는 다음의 함수를 지원함.

* `torch.randint_like(ori, min, max+1)`
* `torch.rand_like(ori)`
* `torch.randn_like(ori)`

In [51]:
ori = torch.tensor([[1.,2.,3.],[4.,5.,6.]])

In [ ]:
torch.randint_like(ori,2,6)

tensor([[3., 4., 3.],
        [3., 4., 3.]])

In [ ]:
torch.rand_like(ori)

tensor([[0.5259, 0.6364, 0.7610],
        [0.4425, 0.1400, 0.8017]])

In [ ]:
torch.randn_like(ori)

tensor([[-1.3659e+00, -1.0878e-03,  1.2655e-01],
        [ 2.7223e-01,  1.5985e-01, -8.8835e-01]])