In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
for i in [np,torch,tf]:
  print( f"{i.__name__}:{i.__version__}")

numpy:1.26.4
torch:2.6.0+cu124
tensorflow:2.18.0


In [ ]:
a = np.arange(6).reshape((3,2)).astype(np.float32)
b = np.ones((3,2),dtype=np.float32)
print(f"{a.dtype=}, {b.dtype=}")

a_t = torch.tensor(a).float()
b_t = torch.tensor(b).float()
print(f"{a_t.dtype=}, {b_t.dtype=}")

a_tf = tf.convert_to_tensor(a,dtype=tf.float32)
b_tf = tf.convert_to_tensor(b,dtype=tf.float32)
print(f"{a_tf.dtype=}, {b_tf.dtype=}")

a.dtype=dtype('float32'), b.dtype=dtype('float32')
a_t.dtype=torch.float32, b_t.dtype=torch.float32
a_tf.dtype=tf.float32, b_tf.dtype=tf.float32


# addition

In [ ]:
c = a + b
print(f"{c=}")
c_t = a_t + b_t
print(f"{c_t=}")
c_tf = a_tf + b_tf
print(f"{c_tf=}")

c=array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)
c_t=tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>


# multiplication

In [ ]:
c = a * b
print(c)
c_t = a_t * b_t
print(c_t)
c_tf = a_tf * b_tf
print(c_tf)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32)


# subtraction

In [ ]:
c = a - b
print(c)
c_t = a_t - b_t
print(c_t)
c_tf = a_tf - b_tf
print(c_tf)

[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]
tensor([[-1.,  0.],
        [ 1.,  2.],
        [ 3.,  4.]])
tf.Tensor(
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]], shape=(3, 2), dtype=float32)


# division

In [ ]:
c = a / b
print(c)
c_t = a_t / b_t
print(c_t)
c_tf = a_tf / b_tf
print(c_tf)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32)


# negation

In [ ]:
c = -a
print(c)
c_t = -a_t
print(c_t)
c_tf = -a_tf
print(c_tf)

[[-0. -1.]
 [-2. -3.]
 [-4. -5.]]
tensor([[-0., -1.],
        [-2., -3.],
        [-4., -5.]])
tf.Tensor(
[[-0. -1.]
 [-2. -3.]
 [-4. -5.]], shape=(3, 2), dtype=float32)


# power and exponentiation

In [ ]:
c = a**2
c_t = a_t**2
c_tf = a_tf**2

print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[ 0.,  1.],
       [ 4.,  9.],
       [16., 25.]], dtype=float32)
c_t =tensor([[ 0.,  1.],
        [ 4.,  9.],
        [16., 25.]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.,  1.],
       [ 4.,  9.],
       [16., 25.]], dtype=float32)>


In [ ]:
# c = np.square(a)
c = np.power(a,2)
c_t = torch.pow(a_t,2)
c_tf = tf.pow(a_tf,2)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[ 0.,  1.],
       [ 4.,  9.],
       [16., 25.]], dtype=float32)
c_t =tensor([[ 0.,  1.],
        [ 4.,  9.],
        [16., 25.]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.,  1.],
       [ 4.,  9.],
       [16., 25.]], dtype=float32)>


In [ ]:
c = np.exp(a)
c_t = torch.exp(a_t)
c_tf = tf.exp(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[  1.       ,   2.718282 ],
       [  7.3890557,  20.085537 ],
       [ 54.59815  , 148.41316  ]], dtype=float32)
c_t =tensor([[  1.0000,   2.7183],
        [  7.3891,  20.0855],
        [ 54.5981, 148.4132]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[  1.       ,   2.7182817],
       [  7.389056 ,  20.085537 ],
       [ 54.59815  , 148.41316  ]], dtype=float32)>


In [ ]:
c = np.exp2(a)
print(c)
c_t = torch.exp2(a_t)
print(c_t)
# c_tf = tf.exp2(a_tf) # not working
# print(c_tf)
c_tf = tf.pow(2.,a_tf)
print(c_tf)

[[ 1.  2.]
 [ 4.  8.]
 [16. 32.]]
tensor([[ 1.,  2.],
        [ 4.,  8.],
        [16., 32.]])
tf.Tensor(
[[ 1.  2.]
 [ 4.  8.]
 [16. 32.]], shape=(3, 2), dtype=float32)


# log (Natural Log)

In [ ]:
c = np.log(a)
c_t = torch.log(a_t)
c_tf = tf.math.log(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[     -inf, 0.       ],
       [0.6931472, 1.0986123],
       [1.3862944, 1.609438 ]], dtype=float32)
c_t =tensor([[  -inf, 0.0000],
        [0.6931, 1.0986],
        [1.3863, 1.6094]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[     -inf, 0.       ],
       [0.6931472, 1.0986123],
       [1.3862944, 1.609438 ]], dtype=float32)>


<ipython-input-69-5e39c409f201>:1: RuntimeWarning: divide by zero encountered in log
  c = np.log(a)


## log2

In [ ]:
c = np.log2(a)
c_t = torch.log2(a_t)
# c_tf = tf.math.log2(a_tf) # not working
c_tf = tf.experimental.numpy.log2(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[     -inf, 0.       ],
       [1.       , 1.5849625],
       [2.       , 2.321928 ]], dtype=float32)
c_t =tensor([[  -inf, 0.0000],
        [1.0000, 1.5850],
        [2.0000, 2.3219]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[     -inf, 0.       ],
       [1.       , 1.5849625],
       [2.       , 2.321928 ]], dtype=float32)>


<ipython-input-65-67042472bafd>:1: RuntimeWarning: divide by zero encountered in log2
  c = np.log2(a)


In [ ]:
c_tf = tf.math.log(a_tf) / tf.math.log(tf.constant(2.0))
print(f"{c_tf = }")

c_tf = <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[     -inf, 0.       ],
       [1.       , 1.5849625],
       [2.       , 2.321928 ]], dtype=float32)>


## common log

In [ ]:
c = np.log10(a)
c_t = torch.log10(a_t)
# c_tf = tf.math.log10(a_tf) # not working
c_tf = tf.experimental.numpy.log10(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[      -inf, 0.        ],
       [0.30103   , 0.47712123],
       [0.60206   , 0.69897   ]], dtype=float32)
c_t =tensor([[  -inf, 0.0000],
        [0.3010, 0.4771],
        [0.6021, 0.6990]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[      -inf, 0.        ],
       [0.30102998, 0.47712126],
       [0.60205996, 0.69897   ]], dtype=float32)>


<ipython-input-67-0ebbc1a7bccb>:1: RuntimeWarning: divide by zero encountered in log10
  c = np.log10(a)


# Square root (제곱근)

In [ ]:
c = np.sqrt(a)
c_t = torch.sqrt(a_t)
c_tf = tf.sqrt(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[0.       , 1.       ],
       [1.4142135, 1.7320508],
       [2.       , 2.236068 ]], dtype=float32)
c_t =tensor([[0.0000, 1.0000],
        [1.4142, 1.7321],
        [2.0000, 2.2361]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.       , 1.       ],
       [1.4142135, 1.7320508],
       [2.       , 2.236068 ]], dtype=float32)>


`pow` 를 이용해도 된다.

In [ ]:
c = np.power   (a   ,1/2)
c_t = torch.pow(a_t ,1/2)
c_tf = tf.pow  (a_tf,1/2)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[0.       , 1.       ],
       [1.4142135, 1.7320508],
       [2.       , 2.236068 ]], dtype=float32)
c_t =tensor([[0.0000, 1.0000],
        [1.4142, 1.7321],
        [2.0000, 2.2361]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.       , 1.       ],
       [1.4142135, 1.7320508],
       [2.       , 2.236068 ]], dtype=float32)>


# absolute value

In [ ]:
c = np.abs(a)
print(c)
c_t = torch.abs(a_t)
print(c_t)
c_tf = tf.abs(a_tf)
print(c_tf)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32)


# Rational Operations

In [ ]:
c = a > b
print(c)
c_t = a_t > b_t
print(c_t)
c_tf = a_tf > b_tf
print(c_tf)

[[False False]
 [ True  True]
 [ True  True]]
tensor([[False, False],
        [ True,  True],
        [ True,  True]])
tf.Tensor(
[[False False]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


# Trigonometric Functions

radian 기준

In [ ]:
c = np.sin(a)
print(c)
c_t = torch.sin(a_t)
print(c_t)
c_tf = tf.sin(a_tf)
print(c_tf)

[[ 0.         0.841471 ]
 [ 0.9092974  0.14112  ]
 [-0.7568025 -0.9589243]]
tensor([[ 0.0000,  0.8415],
        [ 0.9093,  0.1411],
        [-0.7568, -0.9589]])
tf.Tensor(
[[ 0.          0.84147096]
 [ 0.9092974   0.14112   ]
 [-0.7568025  -0.9589243 ]], shape=(3, 2), dtype=float32)


In [ ]:
c = np.cos(a)
print(c)
c_t = torch.cos(a_t)
print(c_t)
c_tf = tf.cos(a_tf)
print(c_tf)

[[ 1.          0.5403023 ]
 [-0.4161468  -0.9899925 ]
 [-0.6536436   0.28366217]]
tensor([[ 1.0000,  0.5403],
        [-0.4161, -0.9900],
        [-0.6536,  0.2837]])
tf.Tensor(
[[ 1.          0.5403023 ]
 [-0.41614684 -0.9899925 ]
 [-0.6536436   0.2836622 ]], shape=(3, 2), dtype=float32)


In [ ]:
c = np.tan(a)
print(c)
c_t = torch.tan(a_t)
print(c_t)
c_tf = tf.tan(a_tf)
print(c_tf)

[[ 0.          1.5574077 ]
 [-2.1850398  -0.14254655]
 [ 1.1578213  -3.380515  ]]
tensor([[ 0.0000,  1.5574],
        [-2.1850, -0.1425],
        [ 1.1578, -3.3805]])
tf.Tensor(
[[ 0.          1.5574077 ]
 [-2.1850398  -0.14254655]
 [ 1.1578213  -3.380515  ]], shape=(3, 2), dtype=float32)


# hyperbolic functions

In [ ]:
c = np.tanh(a)
print(f"{c = }")
c_t = torch.tanh(a_t)
print(f"{c_t = }")
c_tf = tf.tanh(a_tf)
print(f"{c_t = }")

c = array([[0.       , 0.7615942],
       [0.9640276, 0.9950548],
       [0.9993293, 0.9999092]], dtype=float32)
c_t = tensor([[0.0000, 0.7616],
        [0.9640, 0.9951],
        [0.9993, 0.9999]])
c_t = tensor([[0.0000, 0.7616],
        [0.9640, 0.9951],
        [0.9993, 0.9999]])


# Aggregation (집계) 연산


## 전체에 대해서

In [ ]:
c = np.max(a)
print(c)
c_t = torch.max(a_t)
print(c_t)
c_tf = tf.reduce_max(a_tf)
print(c_tf)

5.0
tensor(5.)
tf.Tensor(5.0, shape=(), dtype=float32)


In [ ]:
c = np.min(a)
print(c)
c_t = torch.min(a_t)
print(c_t)
c_tf = tf.reduce_min(a_tf)
print(c_tf)

0.0
tensor(0.)
tf.Tensor(0.0, shape=(), dtype=float32)


In [ ]:
c = np.sum(a)
print(c)
c_t = torch.sum(a_t)
print(c_t)
c_tf = tf.reduce_sum(a_tf)
print(c_tf)

15.0
tensor(15.)
tf.Tensor(15.0, shape=(), dtype=float32)


In [ ]:
c = np.mean(a, axis=0)
print(c)
c_t = torch.mean(a_t, dim=0)
print(c_t)
c_tf = tf.reduce_mean(a_tf, axis=0)
print(c_tf)

[2. 3.]
tensor([2., 3.])
tf.Tensor([2. 3.], shape=(2,), dtype=float32)


## 특정 축(or 차원) 상에서 aggregation

특정 축상에서의 집계 연산시 해당 축이 제거됨.

* 해당 축(or 차원)의 크기가 1이 되므로
* 보관하고자 하면 keep_dim = True를 사용.

In [ ]:
c = np.median(a, axis=0)
print(c)
c_t = torch.median(a_t, dim=0).values # indices도 구함.
print(c_t)
c_tf = tf.math.reduce_mean(a_tf, axis=0)
print(c_tf)

[2. 3.]
tensor([2., 3.])
tf.Tensor([2. 3.], shape=(2,), dtype=float32)


In [ ]:
# pytorch는 indices를 통해 위치도 반환
print(f"{a_t = }")
c_t = torch.median(a_t, dim=0) # indices도 구함.
print(c_t)

a_t = tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
torch.return_types.median(
values=tensor([2., 3.]),
indices=tensor([1, 1]))


In [ ]:
# keepdim은 크기가 1인된 aggregated axis도 보존.
print(f"{a_t.size() = }")
print("---------------")
c_t = torch.max(a_t, dim=0, keepdim=True)
print(f"{c_t.values.size() = }")
print("---------------")
print(f"{c_t = }")

a_t.size() = torch.Size([3, 2])
---------------
c_t.values.size() = torch.Size([1, 2])
---------------
c_t = torch.return_types.max(
values=tensor([[4., 5.]]),
indices=tensor([[2, 2]]))


# boolean operations

In [ ]:
import torch
import numpy as np
import tensorflow as tf

bm0 = a > 2.5
bm1 = a > 3.5
print(f'{bm0=}')
print(f'{bm1=}')
print(f'{bm0.dtype=} / {bm1.dtype=}')
print("-----------------------")
bm0_t = a_t > 2.5
bm1_t = a_t > 3.5
print(f'{bm0_t=}')
print(f'{bm1_t=}')
print("-----------------------")
bm0_tf = a_tf > 2.5
bm1_tf = a_tf > 3.5
print(f'{bm0_tf=}')
print(f'{bm1_tf=}')

bm0=array([[False, False],
       [False,  True],
       [ True,  True]])
bm1=array([[False, False],
       [False, False],
       [ True,  True]])
bm0.dtype=dtype('bool') / bm1.dtype=dtype('bool')
-----------------------
bm0_t=tensor([[False, False],
        [False,  True],
        [ True,  True]])
bm1_t=tensor([[False, False],
        [False, False],
        [ True,  True]])
-----------------------
bm0_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False,  True],
       [ True,  True]])>
bm1_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [ True,  True]])>


In [ ]:
c = bm0 & bm1 # and
print(f"{c=}")
c_t = bm0_t & bm1_t
print(f"{c_t=}")
c_tf = bm0_tf & bm1_tf
print(f"{c_tf=}")

c=array([[False, False],
       [False, False],
       [ True,  True]])
c_t=tensor([[False, False],
        [False, False],
        [ True,  True]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [ True,  True]])>


In [ ]:
c = np.bitwise_and(bm0, bm1)
print(c)
c_t = torch.bitwise_and(bm0_t, bm1_t)
print(c_t)
# c_tf = tf.bitwise.bitwise_and(tf.cast(bm0_tf,tf.int32), tf.cast(bm1_tf, tf.int32))
# print(tf.cast(c_tf,tf.bool))
c_tf = tf.logical_and(bm0_tf, bm1_tf)
print(f"{c_tf=}")

[[False False]
 [False False]
 [ True  True]]
tensor([[False, False],
        [False, False],
        [ True,  True]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [ True,  True]])>


## 참고: TensorFlow에서 bitwise_xxx 연산

* `tf.int32`, `tf.int64` 등의 int 형으로 casting이 필요.

TensorFlow의 경우,

* `|`, `&`, `^`, `~` 등의 연산자에서 operand의 종류에 따라,
* `bitwise_xxx` 가 호출되기도 하고, `logical_xxx`가 호출됨.

In [ ]:
c_tf = tf.bitwise.bitwise_and(tf.cast(bm0_tf,tf.int64), tf.cast(bm1_tf, tf.int64))
print(tf.cast(c_tf,tf.bool))

tf.Tensor(
[[False False]
 [False False]
 [ True  True]], shape=(3, 2), dtype=bool)


## or 연산: `|`

In [ ]:
c = bm0 | bm1 # or
print(f"{c=}")
c_t = bm0_t | bm1_t
print(f"{c_t=}")
c_tf = bm0_tf | bm1_tf
print(f"{c_tf=}")

c=array([[False, False],
       [False,  True],
       [ True,  True]])
c_t=tensor([[False, False],
        [False,  True],
        [ True,  True]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False,  True],
       [ True,  True]])>


## xor 연산: `^`

In [ ]:
c = bm0 ^ bm1 # xor
print(f"{c=}")
c_t = bm0_t ^ bm1_t
print(f"{c_t=}")
c_tf = bm0_tf ^ bm1_tf
print(f"{c_tf=}")

c=array([[False, False],
       [False,  True],
       [False, False]])
c_t=tensor([[False, False],
        [False,  True],
        [False, False]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False,  True],
       [False, False]])>


## not 연산: `~`

In [ ]:
c = ~bm0 # not
print(f"{c=}")
c_t = ~bm0_t
print(f"{c_t=}")
c_tf = ~bm0_tf
print(f"{c_tf=}")

c=array([[ True,  True],
       [ True, False],
       [False, False]])
c_t=tensor([[ True,  True],
        [ True, False],
        [False, False]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True, False],
       [False, False]])>


## 참고: 다음의 코드로 TensorFlow에서 실제 처리를 확인 가능.

TensorFlow는 operand에 따라 bitwise_xxx 와 logical_xxx 중에 하나가 호출됨.

In [ ]:
import tensorflow as tf

@tf.function
def or_test(a, b):
    return a | b  # 논리 OR인지 비트 OR인지 확인

@tf.function
def xor_test(a, b):
    return a ^ b  # 논리 XOR인지 비트 XOR인지 확인

@tf.function
def not_test(a):
    return ~a  # 논리 NOT인지 비트 NOT인지 확인

# 입력값 정의 (bool 텐서)
a = tf.constant([True, False, True, False])
b = tf.constant([False, False, True, True])

# Concrete Function 변환
or_concrete = or_test.get_concrete_function(a, b)
xor_concrete = xor_test.get_concrete_function(a, b)
not_concrete = not_test.get_concrete_function(a)

# 내부 그래프 출력
print("OR Graph:")
print(or_concrete.graph.as_graph_def())

print("\nXOR Graph:")
print(xor_concrete.graph.as_graph_def())

print("\nNOT Graph:")
print(not_concrete.graph.as_graph_def())


OR Graph:
node {
  name: "a"
  op: "Placeholder"
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_user_specified_name"
    value {
      s: "a"
    }
  }
}
node {
  name: "b"
  op: "Placeholder"
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_user_specified_name"
    value {
      s: "b"
    }
  }
}
node {
  name: "or"
  op: "LogicalOr"
  input: "a"
  input: "b"
}
node {
  name: "Identity"
  op: "Identity"
  input: "or"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
versions {
  producer: 1994
}


XOR Graph:
node {
  name: "a"
  op: "Placeholder"
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4
        }
      }
    }
  }
  attr {
    

In [ ]:
# 입력값 정의 (int32 텐서)
a = tf.constant([1, 0, 1, 0])
b = tf.constant([0, 1, 0, 1])

# Concrete Function 변환
or_concrete = or_test.get_concrete_function(a, b)
xor_concrete = xor_test.get_concrete_function(a, b)
not_concrete = not_test.get_concrete_function(a)

# 내부 그래프 출력
print("OR Graph:")
print(or_concrete.graph.as_graph_def())

print("\nXOR Graph:")
print(xor_concrete.graph.as_graph_def())

print("\nNOT Graph:")
print(not_concrete.graph.as_graph_def())

OR Graph:
node {
  name: "a"
  op: "Placeholder"
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_user_specified_name"
    value {
      s: "a"
    }
  }
}
node {
  name: "b"
  op: "Placeholder"
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_user_specified_name"
    value {
      s: "b"
    }
  }
}
node {
  name: "or/BitwiseOr"
  op: "BitwiseOr"
  input: "a"
  input: "b"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Identity"
  op: "Identity"
  input: "or/BitwiseOr"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
versions {
  producer: 1994
}


XOR Graph:
node {
  name: "a"
  op: "Placeholder"
  attr {
    key: "shape"
    value {