In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
for i in [np,torch,tf]:
  print(f"{i.__name__}:{i.__version__}")

numpy:2.0.2
torch:2.6.0+cu124
tensorflow:2.18.0


In [9]:
import timeit

N = 10**6

a = torch.rand(N)
b = torch.rand(N)

dev = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
a = a.to(device=dev) # a,b 둘다 기본 형태는 float 32로 나올거
b = b.to(device=dev)

def vectorized_add(a,b):
  return a+b

def loop_add(a,b):
  result = np.empty(N)
  for i in range(N):
    result[i] = a[i]+b[1]

  return result

torch.cuda.synchronize()
v_p = timeit.timeit("vectorized_add(a,b)",
                    number = 10,
                    globals=globals(),
)
torch.cuda.synchronize()

torch.cuda.synchronize()
l_p = timeit.timeit("loop_add(a,b)",
                    number = 10,
                    globals=globals(),
)
torch.cuda.synchronize()

print(f"{torch.allclose(a,b) = }")

print(f"vectorized add : {v_p:4.6f} sec") # f는 float, 6은 여섯자리까지
print(f"loop add: {l_p:4.6f} sec")

torch.allclose(a,b) = False
vectorized add : 0.000154 sec
loop add: 289.199925 sec


In [ ]:
import timeit

N = 10**6



In [6]:
a = np.arange(6).reshape((3,2)).astype(np.float32)
b = np.ones((3,2),dtype=np.float32)
print(f"{a.dtype=}, {b.dtype=}")

a_t = torch.tensor(a).float() # half는 float16, float은 32,double은 64임
b_t = torch.tensor(b).float()
print(f"{a_t.dtype=}, {b_t.dtype=}")

a_tf = tf.convert_to_tensor(a,dtype=tf.float32)
b_tf = tf.convert_to_tensor(b,dtype=tf.float32)
print(f"{a_tf.dtype=}, {b_tf.dtype=}")

a.dtype=dtype('float32'), b.dtype=dtype('float32')
a_t.dtype=torch.float32, b_t.dtype=torch.float32
a_tf.dtype=tf.float32, b_tf.dtype=tf.float32


# addition

In [7]:
c = a + b
print(f"{c=}")
c_t = a_t + b_t
print(f"{c_t=}")
c_tf = a_tf + b_tf
print(f"{c_tf=}")

c=array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)
c_t=tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>


# multiplication

In [10]:
c = a * b
print(c)
c_t = a_t * b_t
print(c_t)
c_tf = a_tf * b_tf
print(c_tf)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32)


# subtraction

In [11]:
c = a - b
print(c)
c_t = a_t - b_t
print(c_t)
c_tf = a_tf - b_tf
print(c_tf)

[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]
tensor([[-1.,  0.],
        [ 1.,  2.],
        [ 3.,  4.]])
tf.Tensor(
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]], shape=(3, 2), dtype=float32)


# division


In [12]:
c = a / b
print(c)
c_t = a_t / b_t
print(c_t)
c_tf = a_tf / b_tf
print(c_tf)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32)


# negation

In [13]:
c = -a
print(c)
c_t = -a_t
print(c_t)
c_tf = -a_tf
print(c_tf)

[[-0. -1.]
 [-2. -3.]
 [-4. -5.]]
tensor([[-0., -1.],
        [-2., -3.],
        [-4., -5.]])
tf.Tensor(
[[-0. -1.]
 [-2. -3.]
 [-4. -5.]], shape=(3, 2), dtype=float32)


# power & exponentiation

In [14]:
c = a**2
c_t = a_t**2
c_tf = a_tf**2

print(f"{c  =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c  =array([[ 0.,  1.],
       [ 4.,  9.],
       [16., 25.]], dtype=float32)
c_t =tensor([[ 0.,  1.],
        [ 4.,  9.],
        [16., 25.]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.,  1.],
       [ 4.,  9.],
       [16., 25.]], dtype=float32)>


In [16]:
c_t = a_t**(1/3)
c_t

tensor([[0.0000, 1.0000],
        [1.2599, 1.4422],
        [1.5874, 1.7100]])

In [23]:
c_t.square()

tensor([[  0.,   1.],
        [ 16.,  81.],
        [256., 625.]])

In [24]:
c.square() #not working!!!!!!!

AttributeError: 'numpy.ndarray' object has no attribute 'square'

In [25]:
c_t = a_t**(1/2)
c_t

tensor([[0.0000, 1.0000],
        [1.4142, 1.7321],
        [2.0000, 2.2361]])

In [26]:
d_t = torch.sqrt(a_t)
torch.allclose(c_t,d_t)

True

In [17]:
# c = np.square(a)
c = np.power(a,2)
c_t = torch.pow(a_t,2)
c_tf = tf.pow(a_tf,2)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[ 0.,  1.],
       [ 4.,  9.],
       [16., 25.]], dtype=float32)
c_t =tensor([[ 0.,  1.],
        [ 4.,  9.],
        [16., 25.]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.,  1.],
       [ 4.,  9.],
       [16., 25.]], dtype=float32)>


In [19]:
c = np.exp(a)
c_t = torch.exp(a_t)
c_tf = tf.exp(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[  1.       ,   2.718282 ],
       [  7.3890557,  20.085537 ],
       [ 54.59815  , 148.41316  ]], dtype=float32)
c_t =tensor([[  1.0000,   2.7183],
        [  7.3891,  20.0855],
        [ 54.5981, 148.4132]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[  1.       ,   2.7182817],
       [  7.389056 ,  20.085537 ],
       [ 54.59815  , 148.41316  ]], dtype=float32)>


In [20]:
c = np.exp(a)
print(c)
c_t = torch.exp(a_t)
print(c_t)
#c_t = tf.exp2(a_tf) # not working!!!!!!!!!!
#print(c_tf) 얘도!!!!
c_tf = tf.exp(a_tf)
print(c_tf)

[[  1.          2.718282 ]
 [  7.3890557  20.085537 ]
 [ 54.59815   148.41316  ]]
tensor([[  1.0000,   2.7183],
        [  7.3891,  20.0855],
        [ 54.5981, 148.4132]])
tf.Tensor(
[[  1.          2.7182817]
 [  7.389056   20.085537 ]
 [ 54.59815   148.41316  ]], shape=(3, 2), dtype=float32)


# log (natural lod)

In [21]:
c = np.log(a)
c_t = torch.log(a_t)
c_tf = tf.math.log(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[     -inf, 0.       ],
       [0.6931472, 1.0986123],
       [1.3862944, 1.609438 ]], dtype=float32)
c_t =tensor([[  -inf, 0.0000],
        [0.6931, 1.0986],
        [1.3863, 1.6094]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[     -inf, 0.       ],
       [0.6931472, 1.0986123],
       [1.3862944, 1.609438 ]], dtype=float32)>


<ipython-input-21-9674b9c9ff57>:1: RuntimeWarning: divide by zero encountered in log
  c = np.log(a)


# log 2

In [29]:
c = np.log2(a)
c_t = torch.log2(a_t)
#c_tf = tf.math.log2(a_tf) not working!!!!!!!!!!!
c_tf = tf.experimental.numpy.log2(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[     -inf, 0.       ],
       [1.       , 1.5849625],
       [2.       , 2.321928 ]], dtype=float32)
c_t =tensor([[  -inf, 0.0000],
        [1.0000, 1.5850],
        [2.0000, 2.3219]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[     -inf, 0.       ],
       [1.       , 1.5849625],
       [2.       , 2.321928 ]], dtype=float32)>


<ipython-input-29-a9bcd554500b>:1: RuntimeWarning: divide by zero encountered in log2
  c = np.log2(a)


In [30]:
c_tf = tf.math.log(a_tf) / tf.math.log(tf.constant(2.0))
print(f"{c_tf = }")

c_tf = <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[     -inf, 0.       ],
       [1.       , 1.5849625],
       [2.       , 2.321928 ]], dtype=float32)>


# commmon log

In [31]:
c = np.log10(a)
c_t = torch.log10(a_t)
# c_tf = tf.math.log10(a_tf) # not working
c_tf = tf.experimental.numpy.log10(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")
#

c   =array([[      -inf, 0.        ],
       [0.30103   , 0.47712123],
       [0.60206   , 0.69897   ]], dtype=float32)
c_t =tensor([[  -inf, 0.0000],
        [0.3010, 0.4771],
        [0.6021, 0.6990]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[      -inf, 0.        ],
       [0.30102998, 0.47712126],
       [0.60205996, 0.69897   ]], dtype=float32)>


<ipython-input-31-233b6d7b9e13>:1: RuntimeWarning: divide by zero encountered in log10
  c = np.log10(a)


# square root

In [32]:
c = np.sqrt(a)
c_t = torch.sqrt(a_t)
c_tf = tf.math.sqrt(a_tf)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")

c   =array([[0.       , 1.       ],
       [1.4142135, 1.7320508],
       [2.       , 2.236068 ]], dtype=float32)
c_t =tensor([[0.0000, 1.0000],
        [1.4142, 1.7321],
        [2.0000, 2.2361]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.       , 1.       ],
       [1.4142135, 1.7320508],
       [2.       , 2.236068 ]], dtype=float32)>


pow 이용 가능

In [33]:
c = np.power  (a  ,1/2)
c_t = torch.pow(a_t,1/2)
c_tf = tf.pow(a_tf,1/2)
print(f"{c   =}")
print(f"{c_t =}")
print(f"{c_tf=}")
#

c   =array([[0.       , 1.       ],
       [1.4142135, 1.7320508],
       [2.       , 2.236068 ]], dtype=float32)
c_t =tensor([[0.0000, 1.0000],
        [1.4142, 1.7321],
        [2.0000, 2.2361]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.       , 1.       ],
       [1.4142135, 1.7320508],
       [2.       , 2.236068 ]], dtype=float32)>


# absolute value

In [35]:
c = np.abs(a)
print(f"{c   =}")
c_t = torch.abs(a_t)
print(f"{c_t =}")
c_tf = tf.math.abs(a_tf)
print(f"{c_tf=}")

c   =array([[0., 1.],
       [2., 3.],
       [4., 5.]], dtype=float32)
c_t =tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 1.],
       [2., 3.],
       [4., 5.]], dtype=float32)>


# rational op.

In [36]:
c = a > b
print(f"{c   =}")
c_t = a_t > b_t
print(f"{c_t =}")
c_tf = a_tf > b_tf
print(f"{c_tf=}")

c   =array([[False, False],
       [ True,  True],
       [ True,  True]])
c_t =tensor([[False, False],
        [ True,  True],
        [ True,  True]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [ True,  True],
       [ True,  True]])>


# trigonmetric func.
radian.

In [37]:
c = np.sin(a)
print(f"{c   =}")
c_t = torch.sin(a_t)
print(f"{c_t =}")
c_tf = tf.sin(a_tf)
print(f"{c_tf=}")

c   =array([[ 0.       ,  0.841471 ],
       [ 0.9092974,  0.14112  ],
       [-0.7568025, -0.9589243]], dtype=float32)
c_t =tensor([[ 0.0000,  0.8415],
        [ 0.9093,  0.1411],
        [-0.7568, -0.9589]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.        ,  0.84147096],
       [ 0.9092974 ,  0.14112   ],
       [-0.7568025 , -0.9589243 ]], dtype=float32)>


In [39]:
c = np.cos(a)
print(f"{c   =}")
c_t = torch.cos(a_t)
print(f"{c_t =}")
c_tf = tf.cos(a_tf)
print(f"{c_tf=}")
#

c   =array([[ 1.        ,  0.5403023 ],
       [-0.4161468 , -0.9899925 ],
       [-0.6536436 ,  0.28366217]], dtype=float32)
c_t =tensor([[ 1.0000,  0.5403],
        [-0.4161, -0.9900],
        [-0.6536,  0.2837]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.        ,  0.5403023 ],
       [-0.41614684, -0.9899925 ],
       [-0.6536436 ,  0.2836622 ]], dtype=float32)>


In [41]:
c = np.tan(a)
print(f"{c   =}")
c_t = torch.tan(a_t)
print(f"{c_t =}")
c_tf = tf.tan(a_tf)
print(f"{c_tf=}")

c   =array([[ 0.        ,  1.5574077 ],
       [-2.1850398 , -0.14254655],
       [ 1.1578213 , -3.380515  ]], dtype=float32)
c_t =tensor([[ 0.0000,  1.5574],
        [-2.1850, -0.1425],
        [ 1.1578, -3.3805]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.        ,  1.5574077 ],
       [-2.1850398 , -0.14254655],
       [ 1.1578213 , -3.380515  ]], dtype=float32)>


# hyperbolic func.

In [42]:
c = np.tanh(a)
print(f"{c   =}")
c_t = torch.tanh(a_t)
print(f"{c_t =}")
c_tf = tf.tanh(a_tf)
print(f"{c_tf=}")

c   =array([[0.       , 0.7615942],
       [0.9640276, 0.9950548],
       [0.9993293, 0.9999092]], dtype=float32)
c_t =tensor([[0.0000, 0.7616],
        [0.9640, 0.9951],
        [0.9993, 0.9999]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.        , 0.7615942 ],
       [0.9640276 , 0.9950547 ],
       [0.9993292 , 0.99990916]], dtype=float32)>


## Aggregation op.

# 전체 대해서

In [43]:
c = np.max(a)
print(c)
c_t = torch.max(a_t)
print(c_t)
c_tf = tf.reduce_max(a_tf)
print(c_tf)

5.0
tensor(5.)
tf.Tensor(5.0, shape=(), dtype=float32)


In [44]:
c = np.min(a)
print(c)
c_t = torch.min(a_t)
print(c_t)
c_tf = tf.reduce_min(a_tf)
print(c_tf)

0.0
tensor(0.)
tf.Tensor(0.0, shape=(), dtype=float32)


In [45]:
c = np.sum(a)
print(c)
c_t = torch.sum(a_t)
print(c_t)
c_tf = tf.reduce_sum(a_tf)
print(c_tf)

15.0
tensor(15.)
tf.Tensor(15.0, shape=(), dtype=float32)


In [48]:
c = np.mean(a, axis=0)
print(c)
c_t = torch.mean(a_t, dim=0)
print(c_t)
c_tf = tf.reduce_mean(a_tf, axis=0)
print(c_tf)

[2. 3.]
tensor([2., 3.])
tf.Tensor([2. 3.], shape=(2,), dtype=float32)


# 특정 축 차원에서의 aggregation
집계 연산에서 해당 축 제거(특정 축에서)
- 해당 축, 차원의 크기가 1
- 보관하고자 하면 keep_dim =  True 사용

In [56]:
c = np.median(a, axis=0)
print(c)
#print(c.shape)
#c_t = torch.median(a_t, dim=0)
c_t = torch.median(a_t, dim=0).values #indices 구함
print(c_t)
c_tf = tf.math.reduce_mean(a_tf, axis=0)
print(c_tf)

[2. 3.]
tensor([2., 3.])
tf.Tensor([2. 3.], shape=(2,), dtype=float32)


In [52]:
# pytorch는 indices를 통해 위치도 반환
print(f"{a_t = }")
c_t = torch.median(a_t, dim=0) # indices도 구함.
print(c_t)

a_t = tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
torch.return_types.median(
values=tensor([2., 3.]),
indices=tensor([1, 1]))


In [53]:
# keepdim은 크기가 1인된 aggregated axis도 보존.
print(f"{a_t.size() = }")
print("---------------")
c_t = torch.max(a_t, dim=0, keepdim=True)
print(f"{c_t.values.size() = }")
print("---------------")
print(f"{c_t = }")

a_t.size() = torch.Size([3, 2])
---------------
c_t.values.size() = torch.Size([1, 2])
---------------
c_t = torch.return_types.max(
values=tensor([[4., 5.]]),
indices=tensor([[2, 2]]))


집에 가서 2,3,3 으로 해보는 것도 권장하신다고 하시네

# boolean op.

In [57]:
bm0 = a > 2.5
bm1 = a > 3.5
print(f'{bm0=}')
print(f'{bm1=}')
print(f'{bm0.dtype=} / {bm1.dtype=}')
print("-------------------------")
bm0_t = a_t > 2.5
bm1_t = a_t > 3.5
print(f'{bm0_t=}')
print(f'{bm1_t=}')
print("-------------------------")
bm0_tf = a_tf > 2.5
bm1_tf = a_tf > 3.5
print(f'{bm0_tf=}')
print(f'{bm1_tf=}')

bm0=array([[False, False],
       [False,  True],
       [ True,  True]])
bm1=array([[False, False],
       [False, False],
       [ True,  True]])
bm0.dtype=dtype('bool') / bm1.dtype=dtype('bool')
-------------------------
bm0_t=tensor([[False, False],
        [False,  True],
        [ True,  True]])
bm1_t=tensor([[False, False],
        [False, False],
        [ True,  True]])
-------------------------
bm0_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False,  True],
       [ True,  True]])>
bm1_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [ True,  True]])>


In [58]:
c = bm0 & bm1 #and
print(f'{c=}')
c_t = bm0_t & bm1_t
print(f'{c_t=}')
c_tf = bm0_tf & bm1_tf
print(f'{c_tf=}')

c=array([[False, False],
       [False, False],
       [ True,  True]])
c_t=tensor([[False, False],
        [False, False],
        [ True,  True]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [ True,  True]])>


In [62]:
c = np.bitwise_and(bm0, bm1)
print(f'{c=}')
c_t = torch.bitwise_and(bm0_t, bm1_t)
print(f'{c_t=}')
# c_tf = tf.bitwise.bitwise_and(tf.cast(bm0_tf,tf.int32), tf.cast(bm1_tf, tf.int32))
# print(tf.cast(c_tf,tf.bool))
c_tf = tf.logical_and(bm0_tf, bm1_tf)
print(f"{c_tf=}")

c=array([[False, False],
       [False, False],
       [ True,  True]])
c_t=tensor([[False, False],
        [False, False],
        [ True,  True]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [ True,  True]])>


# tf에서는 bitwuse__xxx 연산
- tf.int32, tf.int64 등의 int 형으로 casting이 필요.

TensorFlow의 경우,
- |, &, ^, ~ 등의 연산자에서 operand의 종류에 따라,
- bitwise_xxx 가 호출되기도 하고, logical_xxx가 호출됨.

In [63]:
c_tf = tf.bitwise.bitwise_and(tf.cast(bm0_tf,tf.int32), tf.cast(bm1_tf, tf.int32))
print(tf.cast(c_tf,tf.bool))

tf.Tensor(
[[False False]
 [False False]
 [ True  True]], shape=(3, 2), dtype=bool)


or op.

In [64]:
c = bm0 | bm1 # or op.
print(f'{c=}')
c_t = bm0_t | bm1_t
print(f'{c_t=}')
c_tf = bm0_tf | bm1_tf
print(f'{c_tf=}')

c=array([[False, False],
       [False,  True],
       [ True,  True]])
c_t=tensor([[False, False],
        [False,  True],
        [ True,  True]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False,  True],
       [ True,  True]])>


xor op.

In [65]:
c = bm0 ^ bm1 # xor op.
print(f'{c=}')
c_t = bm0_t ^ bm1_t
print(f'{c_t=}')
c_tf = bm0_tf ^ bm1_tf
print(f'{c_tf=}')

c=array([[False, False],
       [False,  True],
       [False, False]])
c_t=tensor([[False, False],
        [False,  True],
        [False, False]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False,  True],
       [False, False]])>


not op.

In [66]:
c = ~bm0 # not op.
print(f'{c=}')
c_t = ~bm0_t
print(f'{c_t=}')
c_tf = ~bm0_tf
print(f'{c_tf=}')

c=array([[ True,  True],
       [ True, False],
       [False, False]])
c_t=tensor([[ True,  True],
        [ True, False],
        [False, False]])
c_tf=<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True, False],
       [False, False]])>


# tf에서 실제 처리를 확인하는 코드
tf는 operand에 따라 bitwise__XXX 와 logical_XXX 중 하나 호출

In [67]:
import tensorflow as tf

@tf.function
def or_test(a, b):
    return a | b  # 논리 OR인지 비트 OR인지 확인

@tf.function
def xor_test(a, b):
    return a ^ b  # 논리 XOR인지 비트 XOR인지 확인

@tf.function
def not_test(a):
    return ~a  # 논리 NOT인지 비트 NOT인지 확인

# 입력값 정의 (bool 텐서)
a = tf.constant([True, False, True, False])
b = tf.constant([False, False, True, True])

# Concrete Function 변환
or_concrete = or_test.get_concrete_function(a, b)
xor_concrete = xor_test.get_concrete_function(a, b)
not_concrete = not_test.get_concrete_function(a)

# 내부 그래프 출력
print("OR Graph:")
print(or_concrete.graph.as_graph_def())

print("\nXOR Graph:")
print(xor_concrete.graph.as_graph_def())

print("\nNOT Graph:")
print(not_concrete.graph.as_graph_def())


OR Graph:
node {
  name: "a"
  op: "Placeholder"
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_user_specified_name"
    value {
      s: "a"
    }
  }
}
node {
  name: "b"
  op: "Placeholder"
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_user_specified_name"
    value {
      s: "b"
    }
  }
}
node {
  name: "or"
  op: "LogicalOr"
  input: "a"
  input: "b"
}
node {
  name: "Identity"
  op: "Identity"
  input: "or"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
versions {
  producer: 1994
}


XOR Graph:
node {
  name: "a"
  op: "Placeholder"
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4
        }
      }
    }
  }
  attr {
    