In [ ]:
import torch

# GPU 확인.

* `gpu:0` : colon 뒤에 번호를 이용하여 여러 gpu를 구분함.
* 만약 하나만 있다면 `gpu`는 결국 `gpu:0`를 의미.

In [ ]:
print("사용가능한 GPU가 있는가?",
      torch.cuda.is_available())

사용가능한 GPU가 있는가? True


In [ ]:
print("사용가능한 GPU가 몇 개인가?",
      torch.cuda.device_count()) # returns number of available GPU. 1 in my case


사용가능한 GPU가 몇 개인가? 1


In [ ]:
if torch.cuda.is_available():
    print("현재 사용중인 GPU의 index는?",
          torch.cuda.current_device()) # returns index. 0 in my case
else:
    print("GPU가 사용불가능합니다.")

현재 사용중인 GPU의 index는? 0


In [ ]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0)) # Tesla T4
else:
  print("GPU가 사용불가능합니다.")

NVIDIA A100-SXM4-40GB


In [ ]:
a = torch.tensor([1,2,3])
print(a.device)

cpu


In [ ]:
b = a.cpu()      # b = a.to(device='cpu')
print(b.is_cpu)

True


In [ ]:
c = a.to(device='cuda:0') # c = a.cuda()
print(c.is_cuda)

True


In [ ]:
for i in (a,b,c):
  print(i.dtype, i)

torch.int64 tensor([1, 2, 3])
torch.int64 tensor([1, 2, 3])
torch.int64 tensor([1, 2, 3], device='cuda:0')


In [ ]:
b[1] = 999
print(a)
print(b)
print(c) # copy본임을 확인 가능.

tensor([  1, 999,   3])
tensor([  1, 999,   3])
tensor([1, 2, 3], device='cuda:0')


In [ ]:
print(a.untyped_storage().data_ptr())
print(b.untyped_storage().data_ptr())
print(c.untyped_storage().data_ptr())


100057592481536
100057592481536
132504289804288


In [ ]:
# d = a.to(torch.device("cuda"))
d = a.cuda(0)  # d = a.cuda()인 경우 무조건 gpu:0로 할당됨. 번호를 argument로 변경가능.
print(d.is_cuda)

True


In [ ]:
print(a)
print(b)
print(c)
print(d) # 아까 c의 경우와 동일.

tensor([  1, 999,   3])
tensor([  1., 999.,   3.])
tensor([1, 2, 3], device='cuda:0')
tensor([  1, 999,   3], device='cuda:0')


In [ ]:
d[1] = 777
print(a)
print(b)
print(c)
print(d)

tensor([  1, 999,   3])
tensor([  1., 999.,   3.])
tensor([1, 2, 3], device='cuda:0')
tensor([  1, 777,   3], device='cuda:0')


In [ ]:
b = a.to("cpu", torch.float) # dytpe 변경용도로 to를 활용가능함.

print(id(a),a)
print(id(b),b)
print(id(c),c)

132504787224992 tensor([  1, 999,   3])
132504892148208 tensor([  1., 999.,   3.])
132508506569152 tensor([1, 2, 3], device='cuda:0')


In [ ]:
b[1] = 4 # dtype이 바뀌면 data 공유하지 않음.

print(a)
print(b)
print(c)

tensor([  1, 999,   3])
tensor([1., 4., 3.])
tensor([1, 2, 3], device='cuda:0')
